obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.5, -0.45], [-0.50, 0.45], [0.50, 0.45], [0.50, -0.45]]
robot_radius: 0.40

# The radius in meters to which the map inflates obstacle cost values.
inflation_radius: 2.5
cost_scaling_factor: 2.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
